Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from skan import pipe
import toolz as tz


data, per_image_data = tz.last(pipe.process_images(
    schizont_files,
    image_format='fei',
    threshold_radius=5e-8,
    smooth_radius=0.1,
    brightness_offset=0.075,
    scale_metadata_path='Scan/PixelHeight',
    crop_radius=20,
    smooth_method='Gaussian'
))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/toolz/itertoolz.py:343[0m, in [0;36mtail[0;34m(n, seq)[0m
[1;32m    342[0m [38;5;28;01mtry[39;00m:
[0;32m--> 343[0m     [38;5;28;01mreturn[39;00m [43mseq[49m[43m[[49m[38;5;241;43m-[39;49m[43mn[49m[43m:[49m[43m][49m
[1;32m    344[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mTypeError[39;00m, [38;5;167;01mKeyError[39;00m):

[0;31mTypeError[0m: 'generator' object is not subscriptable

During handling of the above exception, another exception occurred:

[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mskan[39;00m [38;5;28;01mimport[39;00m pipe
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mtoolz[39;00m [38;5;28;01mas[39;00m [38;5;21;01mtz[39;00m
[0;32m----> 5[0m data, per_image_data [38;5;241m=[39m [43mtz[49m[38;5;241;43m.[39;49m[43mlast[49m[43m([49m[43mpipe[49m[38;5;241;43m.[39;49m[43mprocess_images[49m[43m([49m
[1;32m      6[0m [43m    [49m[43mschizont_files[49m[43m,[49m
[1;32m      7[0m [43m    [49m[43mimage_format[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mfei[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      8[0m [43m    [49m[43mthreshold_radius[49m[38;5;241;43m=[39;49m[38;5;241;43m5e-8[39;49m[43m,[49m
[1;32m      9[0m [43m    [49m[43msmooth_radius[49m[38;5;241;43m=[39;49m[38;5;241;43m0.1[39;49m[43m,[49m
[1;32m     10[0m [43m    [49m[43mbrightness_offset[49m[38;5;241;43m=[39;49m[38;5;241;43m0.075[39;49m[43m,[49m
[1;32m     11[0m [43m    [49m[43mscale_metadata_path[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mScan/PixelHeight[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m     12[0m [43m    [49m[43mcrop_radius[49m[38;5;241;43m=[39;49m[38;5;241;43m20[39;49m[43m,[49m
[1;32m     13[0m [43m    [49m[43msmooth_method[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mGaussian[39;49m[38;5;124;43m'[39;49m
[1;32m     14[0m [43m)[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/toolz/itertoolz.py:408[0m, in [0;36mlast[0;34m(seq)[0m
[1;32m    402[0m [38;5;28;01mdef[39;00m [38;5;21mlast[39m(seq):
[1;32m    403[0m     [38;5;124;03m""" The last element in a sequence[39;00m
[1;32m    404[0m 
[1;32m    405[0m [38;5;124;03m    >>> last('ABC')[39;00m
[1;32m    406[0m [38;5;124;03m    'C'[39;00m
[1;32m    407[0m [38;5;124;03m    """[39;00m
[0;32m--> 408[0m     [38;5;28;01mreturn[39;00m [43mtail[49m[43m([49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[43mseq[49m[43m)[49m[[38;5;241m0[39m]

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/toolz/itertoolz.py:345[0m, in [0;36mtail[0;34m(n, seq)[0m
[1;32m    343[0m     [38;5;28;01mreturn[39;00m seq[[38;5;241m-[39mn:]
[1;32m    344[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mTypeError[39;00m, [38;5;167;01mKeyError[39;00m):
[0;32m--> 345[0m     [38;5;28;01mreturn[39;00m [38;5;28mtuple[39m([43mcollections[49m[38;5;241;43m.[39;49m[43mdeque[49m[43m([49m[43mseq[49m[43m,[49m[43m [49m[43mn[49m[43m)[49m)

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/skan/pipe.py:161[0m, in [0;36mprocess_images[0;34m(filenames, image_format, threshold_radius, smooth_radius, brightness_offset, scale_metadata_path, crop_radius, smooth_method, num_threads)[0m
[1;32m    159[0m         image_results[38;5;241m.[39mappend(image_stats)
[1;32m    160[0m         [38;5;28;01myield[39;00m filename, image, thresholded, skeleton, framedata
[0;32m--> 161[0m [38;5;28;01myield[39;00m [43mpd[49m[38;5;241;43m.[39;49m[43mconcat[49m[43m([49m[43mresults[49m[43m)[49m, pd[38;5;241m.[39mconcat(image_results)

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/pandas/util/_decorators.py:311[0m, in [0;36mdeprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    305[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m num_allow_args:
[1;32m    306[0m     warnings[38;5;241m.[39mwarn(
[1;32m    307[0m         msg[38;5;241m.[39mformat(arguments[38;5;241m=[39marguments),
[1;32m    308[0m         [38;5;167;01mFutureWarning[39;00m,
[1;32m    309[0m         stacklevel[38;5;241m=[39mstacklevel,
[1;32m    310[0m     )
[0;32m--> 311[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/pandas/core/reshape/concat.py:347[0m, in [0;36mconcat[0;34m(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)[0m
[1;32m    143[0m [38;5;129m@deprecate_nonkeyword_arguments[39m(version[38;5;241m=[39m[38;5;28;01mNone[39;00m, allowed_args[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mobjs[39m[38;5;124m"[39m])
[1;32m    144[0m [38;5;28;01mdef[39;00m [38;5;21mconcat[39m(
[1;32m    145[0m     objs: Iterable[NDFrame] [38;5;241m|[39m Mapping[Hashable, NDFrame],
[0;32m   (...)[0m
[1;32m    154[0m     copy: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mTrue[39;00m,
[1;32m    155[0m ) [38;5;241m-[39m[38;5;241m>[39m DataFrame [38;5;241m|[39m Series:
[1;32m    156[0m     [38;5;124;03m"""[39;00m
[1;32m    157[0m [38;5;124;03m    Concatenate pandas objects along a particular axis with optional set logic[39;00m
[1;32m    158[0m [38;5;124;03m    along the other axes.[39;00m
[0;32m   (...)[0m
[1;32m    345[0m [38;5;124;03m    ValueError: Indexes have overlapping values: ['a'][39;00m
[1;32m    346[0m [38;5;124;03m    """[39;00m
[0;32m--> 347[0m     op [38;5;241m=[39m [43m_Concatenator[49m[43m([49m
[1;32m    348[0m [43m        [49m[43mobjs[49m[43m,[49m
[1;32m    349[0m [43m        [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m,[49m
[1;32m    350[0m [43m        [49m[43mignore_index[49m[38;5;241;43m=[39;49m[43mignore_index[49m[43m,[49m
[1;32m    351[0m [43m        [49m[43mjoin[49m[38;5;241;43m=[39;49m[43mjoin[49m[43m,[49m
[1;32m    352[0m [43m        [49m[43mkeys[49m[38;5;241;43m=[39;49m[43mkeys[49m[43m,[49m
[1;32m    353[0m [43m        [49m[43mlevels[49m[38;5;241;43m=[39;49m[43mlevels[49m[43m,[49m
[1;32m    354[0m [43m        [49m[43mnames[49m[38;5;241;43m=[39;49m[43mnames[49m[43m,[49m
[1;32m    355[0m [43m        [49m[43mverify_integrity[49m[38;5;241;43m=[39;49m[43mverify_integrity[49m[43m,[49m
[1;32m    356[0m [43m        [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m,[49m
[1;32m    357[0m [43m        [49m[43msort[49m[38;5;241;43m=[39;49m[43msort[49m[43m,[49m
[1;32m    358[0m [43m    [49m[43m)[49m
[1;32m    360[0m     [38;5;28;01mreturn[39;00m op[38;5;241m.[39mget_result()

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/pandas/core/reshape/concat.py:404[0m, in [0;36m_Concatenator.__init__[0;34m(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)[0m
[1;32m    401[0m     objs [38;5;241m=[39m [38;5;28mlist[39m(objs)
[1;32m    403[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(objs) [38;5;241m==[39m [38;5;241m0[39m:
[0;32m--> 404[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mNo objects to concatenate[39m[38;5;124m"[39m)
[1;32m    406[0m [38;5;28;01mif[39;00m keys [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    407[0m     objs [38;5;241m=[39m [38;5;28mlist[39m(com[38;5;241m.[39mnot_none([38;5;241m*[39mobjs))

[0;31mValueError[0m: No objects to concatenate
ValueError: No objects to concatenate

